export const SET_CONVERT_TYPE_INIT = "SET_CONVERT_TYPE_INIT";

export const USER_LOGIN_INIT = "USER_LOGIN_INIT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
